### ISSUE TITLE
Search by company

### ISSUE THREAD

**Issue by M-Moeini** [ethbak/connexion-for-linkedin#2]
Hey,
Your code is really cool. I was just thinking to build something like this but I told myself let’s search first and I find this. 

I have 1 question BW.
Is there any option that I search a position based on the company not the location? Let say I want to connect with the engineers of google for say! Is there anyway that I could do this?

Tnx
M

**Comment by ethbak** [comment]
Hi Madhi,

Thanks for the interest in the program! The original use case for the program didn't require being able to search by company.  It should be relatively easy to add. If you want a permanent solution, you will need to update the GUI to have an input for the company which would then be added to the preferences list. The preference list is then input to generate_queries(), which loops over all of the preferences to make all possible combinations of the inputs in the form of detailed search queries, in connexion-for-linkedin\search_tool\google_api.py, so you would need to add support for another input there. 

Id like to add that if you don't care about position and/or location, you could likely just put "google" in for one of those filters and achieve similar results without having to touch any code.

Ethan
